### ISSUE TITLE
walletconnect does not work on ubuntu

### ISSUE THREAD

**Issue by cmagan** [AugustoL/dxdao-alchemy#1]
when clicking the walletconnect logo nothing happens, no barcode...
when exiting the wallet selection section a failure message appears
(in the bottom left)
![image](https://user-images.githubusercontent.com/6940448/82252768-46aaec80-9958-11ea-8193-22f35b856676.png)

Just for reference, same issue was happening on alchemy but somehow recently resolved.
![image](https://user-images.githubusercontent.com/6940448/82253312-6b539400-9959-11ea-8c54-03f8136771dc.png)

**Comment by AugustoL** [comment]
@cmagan should be fixed now in vote.dxtest.eth.link :)
